name: Post Welcome Comment
on:
  pull_request:
    type: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Weclome to the repo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          
